version: "3.8"
services:
  server-1:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SELECTED_REPO: JPA
      SERVER_PORT: 8080
  server-2:
    build: .
    restart: always
    ports:
      - "9090:9090"
    environment:
      SELECTED_REPO: JDBC
      SERVER_PORT: 9090